package increment

// No need to use any #cgo statements because increment.h exists in the same directory as increment.go
// In order to use increment.h you must have an existing lib file. increment.lib was generated by the following:
// gcc -O2 -c increment.c
// ar q increment.lib increment.o

// #include <increment.h>
import "C"

func Increment(i int) int{
	return int(C.x(C.int(i)))
}